version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    environment:
      DISABLE_IPV6_TESTS: "yes"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go get -v -t -d ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
      - run: go build -v .
      - run: go test -v -race -covermode=atomic ./...

workflows:
  main:
    jobs:
      - build
