// Configuration proto for HTTP provider.
//
// Example config:
// probe {
//   targets{
//     http_targets {
//       url: "http://example.com/targets.json"
//       format: JSON
//     }
//   }
// }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.5
// source: github.com/cloudprober/cloudprober/internal/rds/http/proto/config.proto

package proto

import (
	proto1 "github.com/cloudprober/cloudprober/internal/rds/proto"
	proto "github.com/cloudprober/cloudprober/internal/tlsconfig/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderConfig_Format int32

const (
	// UNSPECIFIED = 0;  // Determine format by content negotiation -- Not yet implemented
	ProviderConfig_TEXTPB ProviderConfig_Format = 1 // Text proto format (application/x-textpb).
	ProviderConfig_JSON   ProviderConfig_Format = 2 // JSON proto format (application/json).
)

// Enum value maps for ProviderConfig_Format.
var (
	ProviderConfig_Format_name = map[int32]string{
		1: "TEXTPB",
		2: "JSON",
	}
	ProviderConfig_Format_value = map[string]int32{
		"TEXTPB": 1,
		"JSON":   2,
	}
)

func (x ProviderConfig_Format) Enum() *ProviderConfig_Format {
	p := new(ProviderConfig_Format)
	*p = x
	return p
}

func (x ProviderConfig_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderConfig_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_enumTypes[0].Descriptor()
}

func (ProviderConfig_Format) Type() protoreflect.EnumType {
	return &file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_enumTypes[0]
}

func (x ProviderConfig_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProviderConfig_Format) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProviderConfig_Format(num)
	return nil
}

// Deprecated: Use ProviderConfig_Format.Descriptor instead.
func (ProviderConfig_Format) EnumDescriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescGZIP(), []int{0, 0}
}

// HTTP provider config.
type ProviderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HTTP URL to remote file that contains resources in either textproto or json format.
	// Example in textproto format:
	//
	//	resource {
	//	  name: "switch-xx-01"
	//	  ip: "10.11.112.3"
	//	  port: 8080
	//	  labels {
	//	    key: "device_type"
	//	    value: "switch"
	//	  }
	//	}
	//
	//	resource {
	//	  name: "switch-yy-01"
	//	  ip: "10.16.110.12"
	//	  port: 8080
	//	}
	Url    []string               `protobuf:"bytes,1,rep,name=url" json:"url,omitempty"`
	Format *ProviderConfig_Format `protobuf:"varint,2,req,name=format,enum=cloudprober.rds.http.ProviderConfig_Format" json:"format,omitempty"` // Expected response format -- Required for now
	// TLS config to authenticate communication with the remote server.
	TlsConfig  *proto.TLSConfig `protobuf:"bytes,3,opt,name=tls_config,json=tlsConfig" json:"tls_config,omitempty"`
	TimeoutSec *int32           `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec" json:"timeout_sec,omitempty"`
	// How often resources should be evaluated/expanded.
	ReEvalSec *int32 `protobuf:"varint,99,opt,name=re_eval_sec,json=reEvalSec,def=300" json:"re_eval_sec,omitempty"` // default 5 min
}

// Default values for ProviderConfig fields.
const (
	Default_ProviderConfig_ReEvalSec = int32(300)
)

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderConfig) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *ProviderConfig) GetFormat() ProviderConfig_Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ProviderConfig_TEXTPB
}

func (x *ProviderConfig) GetTlsConfig() *proto.TLSConfig {
	if x != nil {
		return x.TlsConfig
	}
	return nil
}

func (x *ProviderConfig) GetTimeoutSec() int32 {
	if x != nil && x.TimeoutSec != nil {
		return *x.TimeoutSec
	}
	return 0
}

func (x *ProviderConfig) GetReEvalSec() int32 {
	if x != nil && x.ReEvalSec != nil {
		return *x.ReEvalSec
	}
	return Default_ProviderConfig_ReEvalSec
}

type HttpResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource []*proto1.Resource `protobuf:"bytes,1,rep,name=resource" json:"resource,omitempty"`
}

func (x *HttpResources) Reset() {
	*x = HttpResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResources) ProtoMessage() {}

func (x *HttpResources) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResources.ProtoReflect.Descriptor instead.
func (*HttpResources) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *HttpResources) GetResource() []*proto1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto protoreflect.FileDescriptor

var file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDesc = []byte{
	0x0a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x64,
	0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x1a,
	0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x64, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x6c,
	0x73, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x43, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32,
	0x2b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x72, 0x64,
	0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x74, 0x6c, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x74, 0x6c, 0x73, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x54, 0x4c, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x09, 0x74, 0x6c, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x12, 0x23, 0x0a, 0x0b, 0x72, 0x65, 0x5f, 0x65, 0x76, 0x61,
	0x6c, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x63, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x03, 0x33, 0x30, 0x30,
	0x52, 0x09, 0x72, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x22, 0x1e, 0x0a, 0x06, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x45, 0x58, 0x54, 0x50, 0x42, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x02, 0x22, 0x46, 0x0a, 0x0d, 0x48,
	0x74, 0x74, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x72, 0x64, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x72, 0x64, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f,
}

var (
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescData = file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDesc
)

func file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescData)
	})
	return file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_goTypes = []interface{}{
	(ProviderConfig_Format)(0), // 0: cloudprober.rds.http.ProviderConfig.Format
	(*ProviderConfig)(nil),     // 1: cloudprober.rds.http.ProviderConfig
	(*HttpResources)(nil),      // 2: cloudprober.rds.http.HttpResources
	(*proto.TLSConfig)(nil),    // 3: cloudprober.tlsconfig.TLSConfig
	(*proto1.Resource)(nil),    // 4: cloudprober.rds.Resource
}
var file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_depIdxs = []int32{
	0, // 0: cloudprober.rds.http.ProviderConfig.format:type_name -> cloudprober.rds.http.ProviderConfig.Format
	3, // 1: cloudprober.rds.http.ProviderConfig.tls_config:type_name -> cloudprober.tlsconfig.TLSConfig
	4, // 2: cloudprober.rds.http.HttpResources.resource:type_name -> cloudprober.rds.Resource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_depIdxs,
		EnumInfos:         file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_enumTypes,
		MessageInfos:      file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_rawDesc = nil
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_internal_rds_http_proto_config_proto_depIdxs = nil
}
